embedding_size: 64
feat_embed_dim: 64
cf_model: lightgcn

n_ui_layers: [2]
n_mm_layers: [2]
keep_rate: [0.5]

# 
mge_weight: 1.0
use_modality_distillation_loss: False

#
relation_distillation_func: 'CE' # [CE, KL]
behavior_distillation_weight: 1.0
visual_distillation_weight: 1.0
textual_distillation_weight: 1.0
behavior_graph_dropout_threshold: 0
#
image_knn_k: [5,10,15,20]
text_knn_k: [5,10,15,20]
behavior_knn_k: 3000

#
train_batch_size: 2048

cl_weight : [1e-04]
reg_weight: [1e-06]

hyper_parameters: ["n_ui_layers", "n_mm_layers", "keep_rate",  "reg_weight", "image_knn_k", "text_knn_k"]